# Project: web crawler
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Untitled8.o regex.o
LINKOBJ  = Untitled8.o regex.o
LIBS     = -L"C:/Users/Pranav/Desktop/boost_1_60_0" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -L"C:/Users/Pranav/Desktop/boost_1_60_0/boost_1_60_0/libs/regex" -lws2_32 ../../Desktop/wil4c311/WIL32M.LIB ../../Desktop/wil4c311/WIL32M.LIB ../../Desktop/wil4c311/winsock.cpp
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Pranav/Desktop/boost_1_47_0/boost_1_47_0/libs"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Users/Pranav/Desktop/boost_1_47_0" -I"C:/Users/Pranav/Desktop/boost_1_47_0/boost_1_47_0/libs"
BIN      = "web crawler.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

regex.o: regex.cpp
	$(CPP) -c regex.cpp -o regex.o $(CXXFLAGS)
